version: '3.8'  # Always declare the version for explicit compatibility

services:
  db:
    build:
      context: ./db-postgres
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data # persist data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-sample_db}
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    networks:
      - app-network
    depends_on:
      - db
    ports:
      - "${PGADMIN_PORT:-80}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    restart: unless-stopped

  backend:
    networks:
      - app-network
    depends_on:
      - db
    build:
      context: ./spring-boot
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
