spring:
    application:
        name: thutorium
    datasource:
        password: ${POSTGRES_PASSWORD}
        url: jdbc:postgresql://${POSTGRES_URL}:${POSTGRES_PORT}/${POSTGRES_DB}
        username: ${POSTGRES_USER}
    jpa:
        hibernate:
            ddl-auto: create
