name: Deploy Javadoc
run-name: "Publish Javadoc: ${{ github.ref_name }} by ${{ github.actor }}"

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # if you have a protection rule on your repository, you'll need to give write permission to the workflow.
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy JavaDoc 🚀
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc
          java-version: 21
          project: maven
          without-checkout: true
